// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rengifo_Alexander_MVC_Code_First.Data;

#nullable disable

namespace Rengifo_Alexander_MVC_Code_First.Migrations
{
    [DbContext(typeof(Rengifo_Alexander_MVC_Code_FirstContext))]
    [Migration("20240416010152_CambiosBdd")]
    partial class CambiosBdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.EstudianteUdla", b =>
                {
                    b.Property<int>("IdBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBanner"));

                    b.Property<int?>("EstudianteUdlaIdBanner")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBanner");

                    b.HasIndex("EstudianteUdlaIdBanner");

                    b.ToTable("EstudianteUdla");
                });

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.EstudianteUdla", b =>
                {
                    b.HasOne("Rengifo_Alexander_MVC_Code_First.Models.EstudianteUdla", null)
                        .WithMany("Estudiantes")
                        .HasForeignKey("EstudianteUdlaIdBanner");
                });

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.EstudianteUdla", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
