// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rengifo_Alexander_MVC_Code_First.Data;

#nullable disable

namespace Rengifo_Alexander_MVC_Code_First.Migrations
{
    [DbContext(typeof(Rengifo_Alexander_MVC_Code_FirstContext))]
    partial class Rengifo_Alexander_MVC_Code_FirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.EstudianteUdla", b =>
                {
                    b.Property<int>("IdBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBanner"));

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecientoIdRecinto")
                        .HasColumnType("integer");

                    b.Property<int>("VacunaIdVacuna")
                        .HasColumnType("integer");

                    b.HasKey("IdBanner");

                    b.HasIndex("RecientoIdRecinto");

                    b.HasIndex("VacunaIdVacuna");

                    b.ToTable("EstudianteUdla");
                });

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.RecintoVacunacion", b =>
                {
                    b.Property<int>("IdRecinto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecinto"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRecinto");

                    b.ToTable("RecintoVacunacion");
                });

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.Vacuna", b =>
                {
                    b.Property<int>("IdVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacuna"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisProcedencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVacuna");

                    b.ToTable("Vacuna");
                });

            modelBuilder.Entity("Rengifo_Alexander_MVC_Code_First.Models.EstudianteUdla", b =>
                {
                    b.HasOne("Rengifo_Alexander_MVC_Code_First.Models.RecintoVacunacion", "Reciento")
                        .WithMany()
                        .HasForeignKey("RecientoIdRecinto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rengifo_Alexander_MVC_Code_First.Models.Vacuna", "Vacuna")
                        .WithMany()
                        .HasForeignKey("VacunaIdVacuna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reciento");

                    b.Navigation("Vacuna");
                });
#pragma warning restore 612, 618
        }
    }
}
